#!/bin/bash
# =============================================================================
# Agent Battle Command Center - Interactive Setup
# =============================================================================
# Generates secure keys and creates .env from .env.example
#
# Usage:
#   bash scripts/setup.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

echo ""
echo "============================================="
echo "  Agent Battle Command Center - Setup"
echo "============================================="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo "[!] .env already exists at: $ENV_FILE"
  read -p "    Overwrite it? (y/N): " OVERWRITE
  if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
    echo "    Aborted. Your existing .env was not changed."
    exit 0
  fi
  echo ""
fi

# Check .env.example exists
if [ ! -f "$ENV_EXAMPLE" ]; then
  echo "[ERROR] .env.example not found at: $ENV_EXAMPLE"
  exit 1
fi

# Generate secure random hex (portable: try openssl, then python, then /dev/urandom)
generate_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets; print(secrets.token_hex(32))"
  elif command -v python >/dev/null 2>&1; then
    python -c "import os; print(os.urandom(32).hex())"
  elif [ -r /dev/urandom ]; then
    head -c 32 /dev/urandom | xxd -p | tr -d '\n'
  else
    echo "[ERROR] No way to generate random keys. Install openssl or python3." >&2
    exit 1
  fi
}

echo "[1/3] Generating secure keys..."
POSTGRES_PW=$(generate_key)
API_KEY=$(generate_key)
JWT_SECRET=$(generate_key)
echo "      3 secure keys generated."
echo ""

echo "[2/3] Anthropic API Key"
echo "      Get yours at: https://console.anthropic.com/settings/keys"
echo ""
read -p "      Paste your ANTHROPIC_API_KEY (or press Enter to skip): " ANTHROPIC_KEY
if [ -z "$ANTHROPIC_KEY" ]; then
  ANTHROPIC_KEY="sk-ant-api03-CHANGE_ME"
  echo "      Skipped. You can add it to .env later."
  echo "      (Complex tasks won't work without it — Ollama tasks are fine.)"
else
  echo "      Key saved."
fi
echo ""

echo "[3/3] Writing .env..."

cat > "$ENV_FILE" << ENVEOF
# =============================================================================
# Agent Battle Command Center - Environment Configuration
# =============================================================================
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# =============================================================================

# --- Database ---
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PW}
POSTGRES_DB=abcc
# NOTE: DATABASE_URL is only needed for local dev (non-Docker).
# In Docker, the API constructs the connection from the vars above.
DATABASE_URL="postgresql://postgres:${POSTGRES_PW}@localhost:5432/abcc?schema=public"

# --- API Server ---
API_PORT=3001
API_HOST=0.0.0.0
API_KEY=${API_KEY}
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# --- Rate Limiting ---
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=100
RATE_LIMIT_SKIP_SUCCESSFUL=false

# --- Agents Service ---
AGENTS_URL=http://localhost:8000
AGENTS_PORT=8000

# --- UI ---
VITE_API_URL=http://localhost:3001
VITE_WS_URL=ws://localhost:3001
# IMPORTANT: Must be the SAME value as API_KEY above (auto-matched by setup script)
VITE_API_KEY=${API_KEY}

# --- LLM Configuration ---
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

# Ollama (local LLM)
OLLAMA_URL=http://localhost:11434
OLLAMA_API_BASE=http://ollama:11434

# --- Model Settings ---
DEFAULT_MODEL=claude-sonnet-4-5-20250929
FALLBACK_TO_OLLAMA=true
OLLAMA_MODEL=qwen2.5-coder:7b

# --- Human Escalation ---
HUMAN_TIMEOUT_MINUTES=30

# --- JWT ---
JWT_SECRET=${JWT_SECRET}

# --- MCP Gateway (OPTIONAL - disabled by default) ---
USE_MCP=false
MCP_GATEWAY_URL=http://localhost:8001
REDIS_URL=redis://localhost:6379/0
ENVEOF

echo ""
echo "============================================="
echo "  Setup complete!"
echo "============================================="
echo ""
echo "  .env written to: $ENV_FILE"
echo ""
echo "  Keys generated:"
echo "    POSTGRES_PASSWORD  ✓  (auto-matched in DATABASE_URL)"
echo "    API_KEY            ✓  (auto-matched in VITE_API_KEY)"
echo "    JWT_SECRET         ✓"
if [ "$ANTHROPIC_KEY" = "sk-ant-api03-CHANGE_ME" ]; then
  echo "    ANTHROPIC_API_KEY  ✗  (not set — edit .env to add it)"
else
  echo "    ANTHROPIC_API_KEY  ✓"
fi
echo ""
echo "  Next steps:"
echo "    docker compose up --build"
echo ""
echo "  First startup takes ~5-10 minutes (Ollama downloads a 4.7GB model)."
echo "  UI will be at: http://localhost:5173"
echo ""
